### ISSUE TITLE
Error compiling Line 80 File x64\Release\DesktopSaver.exe

### ISSUE THREAD

**Issue by rhgrafix** [npiegdon/desktop-saver#1]
I'm using NSIS by Nullsoft to compile, can't get past Line 80:
File x64\Release\DesktopSaver.exe
I'm using HP Spectre x360 64bit
Thanks

**Comment by npiegdon** [comment]
Be sure to build both the 32 and 64-bit targets in the Visual Studio project before trying to build the installer.  The NSIS script expects both of them to be present (so that it can choose which one should be installed based on your OS).
